'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class gerillaResource
	
	Private Shared resourceMan As Global.System.Resources.ResourceManager
	
	Private Shared resourceCulture As Global.System.Globalization.CultureInfo
	
	<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
	Friend Sub New()
		MyBase.New
	End Sub
	
	'''<summary>
	'''  Returns the cached ResourceManager instance used by this class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
		Get
			If Object.ReferenceEquals(resourceMan, Nothing) Then
				Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("gerilla.gerillaResource", GetType(gerillaResource).Assembly)
				resourceMan = temp
			End If
			Return resourceMan
		End Get
	End Property
	
	'''<summary>
	'''  Overrides the current thread's CurrentUICulture property for all
	'''  resource lookups using this strongly typed resource class.
	'''</summary>
	<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
		Get
			Return resourceCulture
		End Get
		Set
			resourceCulture = value
		End Set
	End Property
	
	Friend Shared ReadOnly Property ge_Icon_Blue() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("ge+Icon-Blue", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property ge_Icon_Green() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("ge+Icon-Green", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property ge_Icon_Magenta() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("ge+Icon-Magenta", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property ge_Icon_Orange() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("ge+Icon-Orange", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property ge_Icon_Red() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("ge+Icon-Red", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property geIcon() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("geIcon", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconAssembly() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconAssembly", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconLibrary() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconLibrary", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconLibrary2() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconLibrary2", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconMaterialMaker() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconMaterialMaker", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconResults() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconResults", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconRunPeriod() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconRunPeriod", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconSimulate() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconSimulate", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconSurface() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconSurface", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconWindow() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconWindow", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
	
	Friend Shared ReadOnly Property GerillaIconZone() As System.Drawing.Bitmap
		Get
			Dim obj As Object = ResourceManager.GetObject("GerillaIconZone", resourceCulture)
			Return CType(obj,System.Drawing.Bitmap)
		End Get
	End Property
End Class
